version: "3"
services:
  app:
    build: .
    tty: true
    depends_on:
      - mysql
    ports:
      - "3000:3000"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-vol

volumes:
  mysql-vol:
