version: "3"
services:
  app:
    build: .
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-auth
    volumes:
      - mysql-data:/var/lib/mysql # For data persistence
      - ./sql:/docker-entrypoint-initdb.d # For database initializing

volumes:
  mysql-data:
