version: "3"
services:
  app:
    image: docker.pkg.github.com/oreotabetai/user-auth-jwt-python-api/user-auth-jwt-python-api:main
    tty: true
    depends_on:
      - mysql
    ports:
      - "3000:3000"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-vol

volumes:
  mysql-vol:
