name: CD
on:
  push:
    branches:
      - main

jobs:
  build_push:
    name: Push to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Container Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: oreotabetai/user-auth-jwt-python-api
          tag_with_ref: true
