name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Building Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: docker-compose build
